let car = 'Nissan';
console.log("Is car == 'Nissan'? I predict True.");
console.log(car == 'Nissan');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
let bike = "Yamaha";
console.log("Is bike == 'Suzuki'? I predict true.");
console.log(bike == "Yamaha");
console.log("Is bike == 'Kawasaki'? I predict true.");
console.log(bike == "Kawasaki");
let second_car = 'Ferrari';
console.log("Is second car == 'Ferrari'? I predict True.");
console.log(second_car == 'Ferrari');
console.log("Is second car == 'Nissan'? I predict False.");
console.log(second_car == 'Nissan');
let third_car = 'Toyota';
console.log("Is third car == 'Toyota'? I predict True.");
console.log(third_car == 'Toyota');
console.log("Is third car == 'Porsche'? I predict False.");
console.log(third_car == 'Porsche');
let mobile = "Samsung";
console.log("Is mobile == 'Samsung'? I predict True.");
console.log(mobile == 'Samsung');
console.log("Is mobile == 'Samsung'? I predict False.");
console.log(mobile == 'Apple');
export {};
